version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: c020c114-577c-4851-a3d0-9ac115013b8a
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  #mounts:
  #  - path: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/myconfig.xml
  #    value: |
  #      <server>
  #          <var name="io_openliberty_sample_system_inMaintenance" value="false"/>
  #      </server>
